version:2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.1-node-browsers
         environment:
           - RAILS_ENV: 'test'
    working_directory: ~/repo
    - run:
      name: run tests
      command: |
        RAILS_ENV=test bundle exec rspec
