version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.2-node-browsers
         environment:
           TZ: Asia/Tokyo
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            bundle exec rspec spec
